language: python
sudo: false

env:
  - LUA="lua=5.1" LUA_COMPAT=default
  - LUA="lua=5.2" LUA_COMPAT=default
  - LUA="lua=5.3" LUA_COMPAT=default
  - LUA="luajit=2.0" LUA_COMPAT=5.2
  - LUA="luajit=2.1" LUA_COMPAT=5.2

before_install:
  - pip install hererocks
  - hererocks lua_install -r^ --$LUA --compat=$LUA_COMPAT
  - export PATH=$PATH:$PWD/lua_install/bin # Add directory with all installed binaries to PATH

install: make test_setup

script:
  - make test
  - make docs

after_success:
  - luacov-coveralls --exclude $TRAVIS_BUILD_DIR/lua_install

branches:
  except:
    - gh-pages
