local outcome = require "outcome"

describe("Option", function()
  describe("when creating Option", function()
    it("returns an instance of Option for empty", function()
      local value = outcome.none()
      assert.equal("outcome.Option", value.class)
    end)

    it("returns an instance of Option for of", function()
      local value = outcome.some("foo")
      assert.equal("outcome.Option", value.class)
      assert.equal("foo", value:unwrap())
    end)

    it("returns None when nil", function()
      local value = outcome.option(nil)
      assert.is_true(value:isNone())
    end)

    it("returns Some when not nil", function()
      local value = outcome.option(1)
      assert.is_true(value:isSome())
    end)
  end)

  describe("when comparing Options", function()
    it("checks for equality", function()
      local a = outcome.some("a")
      local b = outcome.some("a")
      assert.is_true(a == b)
      a = outcome.some("a")
      b = outcome.none()
      assert.is_false(a == b)
    end)

    it("handles Some vs None comparisons", function()
      if string.find(_VERSION, "Lua 5.[23]") then
        local a = outcome.none()
        local b = outcome.some("a")
        assert.is_false(a == b)
        assert.is_true(a < b)
        assert.is_true(a <= b)
      else
        print("Skipping because not on Lua 5.2 or 5.3")
      end
    end)

    it("checks for less than", function()
      local a = outcome.some(1)
      local b = outcome.some(2)
      assert.is_true(a < b)
      assert.is_true(a <= b)
    end)
  end)

  describe("when calling isSome or isNone", function()
    it("handles empty values", function()
      local value = outcome.none()
      assert.is_true(value:isNone())
      assert.is_false(value:isSome())
    end)

    it("handles values", function()
      local value = outcome.some("foo")
      assert.is_false(value:isNone())
      assert.is_true(value:isSome())
    end)
  end)

  describe("when calling ifSome or ifNone", function()
    it("handles empty values", function()
      local value = outcome.none()
      local called = 0
      value:ifSome(function() called = called + 1 end)
      value:ifNone(function() called = called + 2 end)
      assert.equal(2, called)
    end)

    it("handles values", function()
      local value = outcome.some("foo")
      local called = 0
      value:ifSome(function() called = called + 1 end)
      value:ifNone(function() called = called + 2 end)
      assert.equal(1, called)
    end)
  end)

  describe("when unwrapping values", function()
    it("raises error for an empty option", function()
      local value = outcome.none()
      assert.has_error(function() value:unwrap() end,
          "Call to unwrap on a nil value")
      assert.has_error(function() value:expect("Baz!") end, "Baz!")
    end)

    it("returns value when not empty", function()
      local value = outcome.some("foo")
      assert.equal("foo", value:unwrap())
      assert.equal("foo", value:unwrapOr("bar"))
      assert.equal("foo", value:unwrapOrElse(function() return "bar" end))
      assert.equal("foo", value:expect("Missing value?"))
    end)

    it("returns other if none", function()
      local value = outcome.none()
      assert.equal("foo", value:unwrapOr("foo"))
      assert.equal("bar", value:unwrapOrElse(function() return "bar" end))
    end)
  end)

  describe("when composing options", function()
    it("returns other option when option is empty", function()
      local value = outcome.none()
      local result = value:orOther(outcome.some("bar"))
      assert.equal("bar", result:unwrap())
      result = value:orElseOther(function() return outcome.some("bar") end)
      assert.equal("bar", result:unwrap())
    end)

    it("returns self when not empty", function()
      local value = outcome.some("foo")
      local result = value:orOther(outcome.some("bar"))
      assert.equal("foo", result:unwrap())
      result = value:orElseOther(function() return outcome.some("foo") end)
      assert.equal("foo", result:unwrap())
    end)

    it("maps over value when present", function()
      local value = outcome.some(1)
      local result = value:map(function(v) return v + 1 end)
      assert.equal(2, result:unwrap())
      assert.equal(1, value:unwrap())
    end)

    it("does not map over value when value is empty", function()
      local value = outcome.none()
      local result = value:map(error)
      assert.is_true(result:isNone())
    end)

    it("returns default value from mapOr when empty", function()
      local value = outcome.none()
      local result = value:mapOr("foo", error)
      assert.equal("foo", result:unwrap())
    end)

    it("returns mapped value from mapOrElse when not emoty", function()
      local value = outcome.some(1)
      local result = value:mapOrElse(error, function(v) return v + 1 end)
      assert.equal(2, result:unwrap())
    end)

    it("returns result of default value from mapOrElse when empty", function()
      local value = outcome.none()
      local result = value:mapOrElse(function() return "foo" end, error)
      assert.equal("foo", result:unwrap())
    end)

    it("flatmaps over values", function()
      local value = outcome.some(1)
      local result = value:flatmap(function() return outcome.some(2) end, error)
      assert.equal(2, result:unwrap())
    end)

    it("filters Some values", function()
      local value = outcome.some(1)
      local result = value:filter(function(v) return true end)
      assert.equal(1, result:unwrap())
    end)

    it("filters None values", function()
      local value = outcome.none()
      local result = value:filter(function(v) return true end)
      assert.equal(value, result)
    end)
  end)
end)
